### ISSUE TITLE
SubpixelLocalization class biased positions for 3D images.

### ISSUE THREAD

**Issue by tinevez** [imglib/imglib2-algorithm#12]
This bug is responsible for the TrackMate bug fiji/TrackMate#68.

The [SubpixelLocalization](https://github.com/imglib/imglib2-algorithm/blob/master/src/main/java/net/imglib2/algorithm/localextrema/SubpixelLocalization.java) class does not work 'fairly' in 3D. The Y coordinates is off by a considerable factor when localizaing peaks, whereas the X dimension is not affected.

Here are some results on synthetic images. Below I vary the peak position in X from 0 to 1 with 0.1 increments. the Y position of the peak is fixed to be 0.4 + integer.

![subpixel_loc_error_dy0 4_dz0](https://cloud.githubusercontent.com/assets/3583203/10581376/98721ed8-7682-11e5-9fb6-524eda5518e9.png)

The problem is not seen in 2D.

**Comment by StephanPreibisch** [comment]
Nice one :) Thanks @tinevez!
