### ISSUE TITLE
Potential Bug in DiamondShape

### ISSUE THREAD

**Issue by hanslovsky** [imglib/imglib2-algorithm#34]
I recently had an issue in a rather complex scenario including `Views.collapse`, `Views.hyperSlice`, `DiamondShape.neighborhoodsRandomAccessible` and some other view operations.
Starting from a 4D `RAI`, I used `Views.collapse` to collapse the last dimension and iterated over all positions of the last axis of the resulting 3D image, fixing the last dimension to each position `pos` using `Views.hyperSlice`. I then ran some operations on those 2D hyperslices using neighborhoods defined by `DiamondShape`. For each `pos`, instead of looking at the slice at `pos`, the code ran on the slice at 0.

I now managed to create a minimum working example for this ([complete code](https://gist.github.com/hanslovsky/da787d6a50adc34b753dad9f56643d87)):
```java
public static void main( final String[] args )
{
	final long[] dims = { 3, 3, 2, 1 };
	final ArrayImg< FloatType, FloatArray > imgs = ArrayImgs.floats( dims );
	for ( int z = 0; z < dims[ 2 ]; ++z )
		for ( final FloatType h : Views.hyperSlice( imgs, 2, z ) )
			h.set( z );

	final boolean logPosition = false;
	final CompositeIntervalView< FloatType, RealComposite< FloatType > > collapsed = Views.collapseReal( logPosition ? Views.interval( log( imgs ), imgs ) : imgs );

	final int sliceAxis = 2;
	final long slicePos = 1;

	final RandomAccessibleInterval< RealComposite< FloatType > > hs1 = Views.hyperSlice( collapsed, sliceAxis, slicePos );


	final boolean useDiamondShape = true;
	final Shape shape = useDiamondShape ? new DiamondShape( 1 ) : new RectangleShape( 1, false );
	final RandomAccessible< Neighborhood< RealComposite< FloatType > > > nh1 = shape.neighborhoodsRandomAccessible( hs1 );
	final RandomAccessible< Neighborhood< RealComposite< FloatType > > > nh2 = shape.neighborhoodsRandomAccessible( Views.extendValue( hs1, Views.collapseReal( ArrayImgs.floats( 1, dims[ 3 ] ) ).randomAccess().get() ) );

	final long[] xyPosition = { 1, 1 };

	System.out.println( "Outputs should be the same ([1.0] at every position) with or without extension." );

	System.out.println( "Without extension: " );
	iterateAndPrintComposite( nh1.randomAccess(), xyPosition, ( int ) dims[ 3 ] );

	System.out.println( "With extension: " );
	iterateAndPrintComposite( nh2.randomAccess(), xyPosition, ( int ) dims[ 3 ] );
}
```
The code is self-contained except for imglib2 and imglib2-algorithm dependencies and helper methods `log` (log the position of the `RandomAccess` on every call to `get`) and `iterateAndPrintComposite` (iterate over all `Cursor` elements and print the contained `Composite` as well as current position) which are available in the [complete example](https://gist.github.com/hanslovsky/da787d6a50adc34b753dad9f56643d87).

This is what the code does:
 * `imgs` <- Create a 4D `RandomAccessibleInterval`. Each pixel value is set to the pixel's `z-index`.
 * `collapsed` <- Collapse last dimension of `imgs`
 * `hs1` <- Fix last (i.e. third dimension or `z`) of `collapsed` on position `1`.
 * `nh1` <- Create a `RandomAccessible< Neighborhood >` on `hs1`
 * `nh2` <- Create a `RandomAccessible< Neighborhood >` on an extended view of `hs1`
 * Set accesses to `nh1` and `nh2` to center pixel (`[1, 1]`)
 * Iterate over neighborhood for both accesses and print values and position.

I added two parameters for test purposes:
 * `logPosition` if true: Print the position of the `imgs` `RandomAccess` on every `get`.
 * `useDiamondShape` if true: Use `DiamondShape` as neighborhood, `RectangleShape` otherwise.

In any case, the expected output would be
```
...
[1.0] (x,y)
...
```
regardless of the neighborhood or extension. This is true for `RectangleShape`:
```
Outputs should be the same ([1.0] at every position) with or without extension.
Without extension: 
[1.0] (0,0)
[1.0] (1,0)
[1.0] (2,0)
[1.0] (0,1)
[1.0] (1,1)
[1.0] (2,1)
[1.0] (0,2)
[1.0] (1,2)
[1.0] (2,2)
With extension: 
[1.0] (0,0)
[1.0] (1,0)
[1.0] (2,0)
[1.0] (0,1)
[1.0] (1,1)
[1.0] (2,1)
[1.0] (0,2)
[1.0] (1,2)
[1.0] (2,2)
```
When I use `DiamondShape`, however, the output is wrong for the non-extended `RandomAccessibleInterval`:
```
Outputs should be the same ([1.0] at every position) with or without extension.
Without extension: 
[0.0] (1,0)
[0.0] (0,1)
[0.0] (1,1)
[0.0] (2,1)
[0.0] (1,2)
With extension: 
[1.0] (1,0)
[1.0] (0,1)
[1.0] (1,1)
[1.0] (2,1)
[1.0] (1,2)
```
Additional logging (every line starting with `Pos is:`) of the source `RandomAccess` at every `get` shows that the `RandomAccess` that looks into `imgs` is set to `0` instead of `1` for the third dimension when no extension is used:
```
Outputs should be the same ([1.0] at every position) with or without extension.
Without extension: 
Pos is: (1,0,0,0)
[0.0] (1,0)
Pos is: (0,1,0,0)
[0.0] (0,1)
Pos is: (1,1,0,0)
[0.0] (1,1)
Pos is: (2,1,0,0)
[0.0] (2,1)
Pos is: (1,2,0,0)
[0.0] (1,2)
With extension: 
Pos is: (1,0,1,0)
[1.0] (1,0)
Pos is: (0,1,1,0)
[1.0] (0,1)
Pos is: (1,1,1,0)
[1.0] (1,1)
Pos is: (2,1,1,0)
[1.0] (2,1)
Pos is: (1,2,1,0)
[1.0] (1,2)
```

I wasn't able to find out the precise cause of this but it seems to be specific to `DiamondShape` in conjunction with `Views.collapse` and `Views.hyperSlice`.

**Comment by hanslovsky** [comment]
I just found out together with @axtimwalde that this example also fails for `HyperSphereShape`.

**Comment by tpietzsch** [comment]
Found it. `CompositeRandomAccess.copy()` didn't work. This https://github.com/imglib/imglib2/compare/compositefix fixes it.

@axtimwalde @hanslovsky Could you check whether there is other places in the Composite framework where this problem might occur?

**Comment by hanslovsky** [comment]
That was a quick find, I am impressed!
I will have a look.
