### ISSUE TITLE
Remove imagej-common dependency

### ISSUE THREAD

**Issue by tpietzsch** [imglib/imglib2-algorithm#43]
We should get rid of the imagej-common dependency. It is only needed in DoG to get image calibration from `net.imagej.space.LinearSpace`. This should not happen here. Just move it to ops.

**Comment by acardona** [comment]
A possible solution: let the calibration be given as argument. No need to have it discovered automatically.

**Comment by hanslovsky** [comment]
Agreed. That would mean we do not need this constructor anymore:
https://github.com/imglib/imglib2-algorithm/blob/master/src/main/java/net/imglib2/algorithm/dog/DogDetection.java#L81-L89
Going through the code, I also realized that the parameter `boolean normalizeMinPeakValue` is never used in one of the constructors (instead `true` is passed):
https://github.com/imglib/imglib2-algorithm/blob/master/src/main/java/net/imglib2/algorithm/dog/DogDetection.java#L98

**Comment by tpietzsch** [comment]
> Going through the code, I also realized that the parameter boolean normalizeMinPeakValue is never used in one of the constructors (instead true is passed):
> https://github.com/imglib/imglib2-algorithm/blob/master/src/main/java/net/imglib2/algorithm/dog/DogDetection.java#L98

uh, wow, thats clearly a bug :-(

**Comment by ctrueden** [comment]
Regression test time!

**Comment by tpietzsch** [comment]
what do you mean by that?

**Comment by ctrueden** [comment]
@tpietzsch I just meant that there should be a `DogDetectionTest` which exercises it with `normalizeMinPeakValue` set to both `true` and `false`.

Maybe this would be a good student project, going through `imglib2-algorithm` and adding many regression tests, since lots of the algorithms do not have any.

**Comment by hanslovsky** [comment]
I deprecated that constructor in 2e661a0
That way, we can remove the constructor in the future (and thus the imagej-common dependency). If we all agree that this is the way to go forward, I'll create a PR.

**Comment by tpietzsch** [comment]
Sounds good! I would also be fine with removing the constructor right away.

While you are at it, could you also fix the bug that you discovered?
> Going through the code, I also realized that the parameter boolean normalizeMinPeakValue is never used in one of the constructors (instead true is passed):
> https://github.com/imglib/imglib2-algorithm/blob/master/src/main/java/net/imglib2/algorithm/dog/DogDetection.java#L98

**Comment by hanslovsky** [comment]
I would prefer to remove the constructor right away as well. I was just worried about breaking changes. If that is not an issue, I will remove the constructor right away.

Regarding the bug: I will do that, too.
