### ISSUE TITLE
Merge fixDependencies branch as soon as possible and re-distribute JAR's

### ISSUE THREAD

**Issue by StephanPreibisch** [imglib/imglib2-algorithm#49]
Hi @tpietzsch @axtimwalde @ctrueden,

we discussed the same problem some time ago. The current version of imglib2-algorithm is compiled against imglib2-3.3.0 and not the current 4.6.0. 

This results in the problem that any algorithm that makes a CellImg crashes since the CellImg constructor changed from imglib2-3.*.* to imglib2-4.*.* (for example Gauss3 on images > 2^31 pixels).

This is very critical for our applications. We should just merge the branch containing my "fix" https://github.com/imglib/imglib2-algorithm/commit/0f6c1fdf1e83ef8428dce3539c0b4d1f49ad0df8

and re-distribute ASAP.

Cheers,
Stephan

**Comment by imagejan** [comment]
(See also https://github.com/scijava/pom-scijava/issues/50)

**Comment by StephanPreibisch** [comment]
Yes, that was it, thanks :)

I fixed it locally on the BigStitcher update site where I made a pre-release of https://github.com/imglib/imglib2-algorithm/commit/0f6c1fdf1e83ef8428dce3539c0b4d1f49ad0df8 which works

**Comment by hanslovsky** [comment]
This should be fixed. imglib2-algorithm currently has pom-imglib2:10.0.1 as parent, which in turn has pom-scijava:19.0.0 as parent, which defines `<imglib2.version>4.6.0</imglib2.version>`.
Re-open if necessary.
