### ISSUE TITLE
EllipseTest is slow

### ISSUE THREAD

**Issue by hanslovsky** [imglib/imglib2-algorithm#52]
I just noticed that the `EllipseTest` is very slow: In this example it took more than 11 seconds ( I added context for comparison).
```
Running net.imglib2.algorithm.region.EllipseTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.481 sec - in net.imglib2.algorithm.region.EllipseTest
```
```
Running net.imglib2.algorithm.hessian.HessianMatrixTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.057 sec - in net.imglib2.algorithm.hessian.HessianMatrixTest
Running net.imglib2.algorithm.hessian.HessianMatrixEigenValuesTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec - in net.imglib2.algorithm.hessian.HessianMatrixEigenValuesTest
Running net.imglib2.algorithm.localextrema.SubpixelLocalizationTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.051 sec - in net.imglib2.algorithm.localextrema.SubpixelLocalizationTest
Running net.imglib2.algorithm.region.EllipseTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.481 sec - in net.imglib2.algorithm.region.EllipseTest
Running net.imglib2.algorithm.region.CircleTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.228 sec - in net.imglib2.algorithm.region.CircleTest
Running tests.labeling.ConnectedComponentsTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.119 sec - in tests.labeling.ConnectedComponentsTest
Running tests.labeling.WatershedTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 sec - in tests.labeling.WatershedTest
Running tests.labeling.AllConnectedComponentsTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.039 sec - in tests.labeling.AllConnectedComponentsTest
```

This inreases the build-time of imglib2-algorithm unnecessarily.
[`testIterateOnce`](https://github.com/imglib/imglib2-algorithm/blob/912451b554d53b9a87a3f7af07407438450d79b9/src/test/java/net/imglib2/algorithm/region/EllipseTest.java#L18-L42) is run for `55 * 55 = 3025` times for all combinations for two radii `1 <= rx, ry <= 55` and [creates a new `String` object in every iteration of the innermost loop](https://github.com/imglib/imglib2-algorithm/blob/912451b554d53b9a87a3f7af07407438450d79b9/src/test/java/net/imglib2/algorithm/region/EllipseTest.java#L33-L34). I also think the benefits of this methods are very limited as it essentially tests cursor iteration by cursor iteration.

[`testDistanceToCenter`](https://github.com/imglib/imglib2-algorithm/blob/912451b554d53b9a87a3f7af07407438450d79b9/src/test/java/net/imglib2/algorithm/region/EllipseTest.java#L45-L72) creates [`String objects in the innermost loop`](https://github.com/imglib/imglib2-algorithm/blob/912451b554d53b9a87a3f7af07407438450d79b9/src/test/java/net/imglib2/algorithm/region/EllipseTest.java#L68) as well.

I suggest we remove `testIterateOnce` and avoid the creation of objects in the inner loop of `testDistanceToCenter`:
```
Running net.imglib2.algorithm.region.EllipseTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.036 sec - in net.imglib2.algorithm.region.EllipseTest
```

Please comment.

**Comment by hanslovsky** [comment]
Changes would look like this:
2f26c7b725c56be6db1b3ad8815464ba235b2498

**Comment by hanslovsky** [comment]
@tinevez would you be d'accord if I removed the lines as indiciated in 2f26c7b725c56be6db1b3ad8815464ba235b2498?

**Comment by tinevez** [comment]
I would be completement d'accord.
