### ISSUE TITLE
RectangleNeighborhoodCursor.jumpFwd(1) results in incorrect position.

### ISSUE THREAD

**Issue by Squareys** [imglib/imglib2-algorithm#6]
Hi @tpietzsch !

I believe I found a bug in RectangleNeighborhoodCursor:

On a fresh `shape.neighborhoodsSafe(img).localizingCursor()` `fwd()` results in position `[0, 0, 0]`, but
`jumpFwd(1)` results in position `[2, 0, 0]`.

I wrote a simple test for this: [here](https://github.com/Squareys/imglib2-algorithm/blob/test-rectangle-shape/src/test/java/net/imglib2/algorithm/neighborhood/RectangleShapeTest.java)

When letting the cursor run through the entire img with `.jumpFwd(1)`, an `ArrayIndexOutOfBoundsException` is thrown.

Greetings, Squareys

**Comment by dietzc** [comment]
https://github.com/imglib/imglib2-algorithm/tree/fix-rectangle-jump

Does this work as expected?
